### ISSUE TITLE
InvalidDataException when posting IFormFile [DotNetCore]

### ISSUE THREAD

**Issue by tomdebie** [flakey-bit/DotNetDigestAuth#2] opened 2019-03-21 15:06 UTC
Hello,

I'm using multipart/form-data to upload a file and want to protect it using digest authentication.
Without the Authorize attribute the test file gets read without any issue. The file is small enough (100kB) to pass through without hitting any dotnet core limits.

Using digest authentication I suddenly get:
InvalidDataException: Multipart body length limit 16384 exceeded.

Among other things I've tried setting [RequestSizeLimit(long.MaxValue)] on the action and configuring the global MultipartBodyLengthLimit to a higher limit but with no success.

Since it seems to work without authentication I believe it is somehow related.
Any ideas?

I've attached a small example to reproduce.

```[HttpPost]
[Authorize(AuthenticationSchemes = "Digest")]
public async Task<IActionResult> PostFormData([FromForm] IFormFile file)
{
          using (var sr = new StreamReader(file.OpenReadStream()))
          {
                    var content = await sr.ReadToEndAsync();
                    return Ok(content);
          }
}
```

**Comment by flakey-bit** [comment] 2019-03-21 22:35
I tried to reproduce this issue but could not.

I was using the form below & a 900kb file.

```csharp
<form method="POST" enctype="multipart/form-data">
    <input type="file" name="file">
    <input type="submit" name="submit">
</form>
```

Please provide more information on how to reproduce.

**Comment by flakey-bit** [comment] 2019-03-22 05:37
Perhaps you can modify the sample project ("AspNetCoreApp" in the source) to show/reproduce the issue?

**Comment by tomdebie** [comment] 2019-03-22 09:37
I created a request in postman to test it out. Attached the test file and exported the request below.
[digest_postman.zip](https://github.com/flakey-bit/DotNetDigestAuth/files/2995843/digest_postman.zip)
![image](https://user-images.githubusercontent.com/7985834/54813669-5e241200-4c8e-11e9-8002-d8abc0425940.png)


I'll modify the sample project to reproduce when I get home tonight.

**Comment by flakey-bit** [comment] 2019-03-23 01:17
Note that your Postman request had the authentication headers (incl 'nonce') saved. After clearing those deatils I can reproduce this issue.

![image](https://user-images.githubusercontent.com/4413825/54859390-34cfb880-4d58-11e9-93a7-6e4e2e4da6cc.png)

Interestingly, I see the exact same issue with the authentication library completely removed from the project & the following controller code:

```csharp
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
//        // GET api/values
        [HttpGet]
        public IActionResult Get() {
            var formHtml = @"
<form enctype=""multipart/form-data"" method=""POST"">
    <input type=""file"" name=""file"">
    <input type=""submit"" name=""submit"">
</form>";
            return Content(formHtml, "text/html");
        }

        public async Task<IActionResult> PostFormData(/*[FromForm] IFormFile file*/)
        {
            var files = Request.Form.Files;
            var f = files[0];
            return Ok();
        }
    }
```

**Comment by flakey-bit** [comment] 2019-03-23 12:56
Hi,

It looks as though Postman is generating invalid requests. 

I have removed the "Content-Type" header from the request in Postman (as advised online, Postman should generate a correct "Content-Type" header for you:

![image](https://user-images.githubusercontent.com/4413825/54866199-bd804000-4dbc-11e9-8837-d7aa65a0b159.png)

This is the request (from Postman 6.0.10) as captured in Fiddler:

![image](https://user-images.githubusercontent.com/4413825/54866249-2ff12000-4dbd-11e9-9a5d-6c3ba2978532.png)

As you can see, the "boundary" on the `content-type` header i.e. `658540084194489423972374` is not being used. 

Contrast this with the request made from Chrome: 

![image](https://user-images.githubusercontent.com/4413825/54866278-75155200-4dbd-11e9-9254-c2470c20131a.png)

Where the "boundary" on the `content-type` header i.e. `WebKitFormBoundaryoR13k1Jgg5pAnJ3U` is used correctly.

If I remove the authorization header from Postman then it sets the boundary correctly:

![image](https://user-images.githubusercontent.com/4413825/54866355-75fab380-4dbe-11e9-8eb8-dd2c1b1a3dc0.png)

I tried updating to the very latest version of Postman - it did not help. I suggest raising a bug with the Postman team.

Closing this issue as the problem is with Postman (multipart/form-data file upload works fine from a web browser).

**Closed as completed by flakey-bit** 2019-03-23 12:56 UTC

**Comment by tomdebie** [comment] 2019-03-23 14:45
Thx Eddie!
This taught me a bunch! Thx for all your time and the cool library ;)

**Comment by flakey-bit** [comment] 2019-03-24 00:18
Have opened issue https://github.com/postmanlabs/postman-app-support/issues/6140 with Postman
